### ISSUE TITLE
Can no longer use AAOptionsConstructor.configureAAOptions in new release

### ISSUE THREAD

**Issue by jamesot** [AAChartModel/AAChartKit-Swift#161]
Hey, I just updated my project and I can no longer use `AAOptionsConstructor.configureAAOptions` .. would you mind pointing to the new documentation of what replace this?

I've also tried using the below line and its not working. Would you mind helping tell what might be wrong?
![Screen Shot 2019-09-05 at 5 16 52 AM](https://user-images.githubusercontent.com/25936226/64306730-72d63700-cf9c-11e9-8d60-805fb0cd48f8.png)

**Comment by AAChartModel** [comment]
Fixed it now! Update to latest version and try it again.

**Comment by pmlican** [comment]
still not fix. class name replace by AAOptionsConstructor. and can not use AAOptionsConstructor static function
